name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure full history is fetched for analysis
      - name: Pull Blacklock Code Scanner Docker Image
        run: docker pull blacklocksec/code-scanner:latest
      - name: Run Blacklock Code Scanner
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -e SONAR_PROJECTKEY="${{ secrets.PROJECTKEY }}" \
            blacklocksec/code-scanner:latest
